name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Build
      run: |
        npm run build